### Site Settings ###
title               : David Phoon's CV
description         : "Welcome to my digital abode"
baseurl             : "/cv"
repository          : davidphoonzy/cv
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/blog.html

### Author Info ###
author:
  name              : David Phoon
  image             : assets/frontpic.jpg
# behance           : your_username
# dribbble          : your_username
  email             : davidphoonzy@gmail.com
# facebook          : your_username
  github            : davidphoonzy
# gitlab            : your_username
# instagram         : your_username
  linkedin          : dpzy
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  certs:
    output: true
    permalink: /certs/:name
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections - certs and project ###
defaults:
  - scope:
      path: "certs"
      type: "certs"
    values:
      layout: "certlay"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "projectlay"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - _posts/"eg*.md"
  - _data/timeline.yml
