### Site Settings ###
title               : David Phoon's CV
description         : "David's Portfolio"
url             : "/cv"
repository          : davidphoonzy/cv

markdown: kramdown

### Author Info ###
author:
  name              : David Phoon
  image             : assets/frontpic.jpg
  email             : davidphoonzy@gmail.com
  github            : davidphoonzy

### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  sections:
    output: true
  section-certs:
    output: false
    permalink: /section-certs/:name
  section-projects:
    output: true
    permalink: /section-projects/:name
  section-writings:
    output: true
    permalink: /section-writings/:name

defaults:
  - scope:
      path: ""
      type: ""
    values:
      layout: ""


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - _posts/"eg*.md"
  - _data/timeline.yml
