### Site Settings ###
title               : David Phoon's CV
description         : >-
                      "I am a penguin :penguin:."
baseurl             : "/cv"
repository          : davidphoonzy/cv
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - pages/about.md
  - pages/blog.html


### Author Info ###
author:
  name              : David Phoon
  image             : https://www.nationalgeographic.com/content/dam/news/photos/000/676/67655.adapt.676.1.jpg
# behance           : your_username
# dribbble          : your_username
  email             : davidphoonzy@gmail.com
# facebook          : your_username
  github            : davidphoonzy
# gitlab            : your_username
# instagram         : your_username
  linkedin          : dpzy
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
# twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page2"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
